### ISSUE TITLE
损失函数

### ISSUE THREAD

**Issue by ElliottZhen** [LiYunfengLYF/LightFC#8]
你好，打扰了~
很棒的工作的！
请问你在消融实验中Wiou用的是哪个版本呢，是V1吗？
@LiYunfengLYF

**Comment by LiYunfengLYF** [comment]
> 你好，打扰了~ 很棒的工作的！ 请问你在消融实验中Wiou用的是哪个版本呢，是V1吗？ @LiYunfengLYF

我是在网上找的一个wiou的快速实现方法，该方法把几种iou都集成起来了，以便我们快速实现想法，我也没太搞懂wiou的不同版本问题。从yolo6也不是yolo7那里获得的启发，各种iou挨个莽过去，哪个好用用哪个，

**Comment by ElliottZhen** [comment]
好的，我再看看，非常感谢你开源的许多代码，学到了很多！
